/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tk' | 'en') | ('tk' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'home-hero': HomeHero;
    'home-production': HomeProduction;
    'home-brand-statement': HomeBrandStatement;
    'home-services': HomeService;
    'home-process': HomeProcess;
    'services-header': ServicesHeader;
    'about-intro': AboutIntro;
    'about-capabilities': AboutCapability;
    'about-contact': AboutContact;
    privacy: Privacy;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'home-production': HomeProductionSelect<false> | HomeProductionSelect<true>;
    'home-brand-statement': HomeBrandStatementSelect<false> | HomeBrandStatementSelect<true>;
    'home-services': HomeServicesSelect<false> | HomeServicesSelect<true>;
    'home-process': HomeProcessSelect<false> | HomeProcessSelect<true>;
    'services-header': ServicesHeaderSelect<false> | ServicesHeaderSelect<true>;
    'about-intro': AboutIntroSelect<false> | AboutIntroSelect<true>;
    'about-capabilities': AboutCapabilitiesSelect<false> | AboutCapabilitiesSelect<true>;
    'about-contact': AboutContactSelect<false> | AboutContactSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
  };
  locale: 'tk' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Used by the detail URL, for example: /service/marketing
   */
  slug: string;
  /**
   * Controls the order on the Services catalog page.
   */
  sortOrder: number;
  /**
   * Short description displayed on the Services catalog page.
   */
  catalogSummary: string;
  icon?: (number | null) | Media;
  detailDescription: string;
  heroImage?: (number | null) | Media;
  offeringsHeading?: string | null;
  /**
   * Offerings belong only to this service detail page.
   */
  offerings?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  processHeading?: string | null;
  process?:
    | {
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  locale?: ('all' | 'tk' | 'en') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sortOrder?: T;
  catalogSummary?: T;
  icon?: T;
  detailDescription?: T;
  heroImage?: T;
  offeringsHeading?: T;
  offerings?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  processHeading?: T;
  process?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Primary organization logo used in site-wide structured data.
   */
  logo?: (number | null) | Media;
  /**
   * Browser tab icon used across the website.
   */
  favicon?: (number | null) | Media;
  websiteJsonLd: {
    name: string;
    /**
     * Describes the website itself, separately from any page meta description.
     */
    description?: string | null;
    alternateNames?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  organizationJsonLd: {
    name: string;
    legalName?: string | null;
    description?: string | null;
    email?: string | null;
    telephone?: string | null;
    streetAddress?: string | null;
    addressLocality?: string | null;
    addressCountry?: string | null;
    socialProfiles?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  additionalJsonLd?: {
    /**
     * Optional structured-data objects that apply across the entire website.
     */
    entries?:
      | {
          name: string;
          enabled?: boolean | null;
          /**
           * Enter one complete schema.org object. @context is added automatically when omitted.
           */
          data:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  servicesLabel: string;
  informationLabel: string;
  turkmenLanguageLabel: string;
  englishLanguageLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  cookiePolicyLabel: string;
  privacyPolicyLabel: string;
  copyright: string;
  credit: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  location?: string | null;
  headline: string;
  supportingText?: string | null;
  email: string;
  copySuccessLabel?: string | null;
  /**
   * Browser title and social sharing title for the home page.
   */
  metaTitle: string;
  /**
   * Search-engine and social sharing description for the home page.
   */
  metaDescription: string;
  /**
   * Open Graph and social sharing image for the home page.
   */
  metaImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-production".
 */
export interface HomeProduction {
  id: number;
  projects?:
    | {
        clientName: string;
        projectName: string;
        coverImage: number | Media;
        video: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-brand-statement".
 */
export interface HomeBrandStatement {
  id: number;
  statement: string;
  /**
   * Scrolling text displayed along the bottom of the Marketing section.
   */
  marqueeText: string;
  /**
   * Displayed until the desktop video is ready, or permanently when no desktop video is uploaded.
   */
  desktopCoverImage?: (number | null) | Media;
  desktopVideo?: (number | null) | Media;
  /**
   * Displayed until the mobile video is ready, or permanently when no mobile video is uploaded.
   */
  mobileCoverImage?: (number | null) | Media;
  mobileVideo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-services".
 */
export interface HomeService {
  id: number;
  eyebrow?: string | null;
  items?:
    | {
        title: string;
        description: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-process".
 */
export interface HomeProcess {
  id: number;
  items?:
    | {
        title: string;
        description: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-header".
 */
export interface ServicesHeader {
  id: number;
  title: string;
  introduction?: string | null;
  /**
   * Browser title and social sharing title for the Services catalog page.
   */
  metaTitle: string;
  /**
   * Search-engine and social sharing description for the Services catalog page.
   */
  metaDescription: string;
  /**
   * Open Graph and social sharing image for the Services catalog page.
   */
  metaImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-intro".
 */
export interface AboutIntro {
  id: number;
  statement: string;
  image?: (number | null) | Media;
  /**
   * Browser title and social sharing title for the Information page.
   */
  metaTitle: string;
  /**
   * Search-engine and social sharing description for the Information page.
   */
  metaDescription: string;
  /**
   * Open Graph and social sharing image for the Information page.
   */
  metaImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-capabilities".
 */
export interface AboutCapability {
  id: number;
  capabilitiesHeading?: string | null;
  capabilitiesText?: string | null;
  clientsHeading?: string | null;
  clients?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-contact".
 */
export interface AboutContact {
  id: number;
  contactHeading?: string | null;
  contactLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  officeHeading?: string | null;
  address?: string | null;
  hoursHeading?: string | null;
  workingDays?: string | null;
  workingHours?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: number;
  privacyTitle: string;
  privacyLastUpdatedLabel?: string | null;
  privacyLastUpdated?: string | null;
  privacySections?:
    | {
        heading: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  privacyMetaTitle: string;
  privacyMetaDescription: string;
  privacyMetaImage?: (number | null) | Media;
  cookieTitle: string;
  cookieOverviewLabel?: string | null;
  cookieOverviewContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cookieDomainLabel?: string | null;
  cookieDomain?: string | null;
  cookieConsentSectionLabel?: string | null;
  cookieCurrentStateLabel?: string | null;
  cookieConsentIdLabel?: string | null;
  cookieConsentDateLabel?: string | null;
  cookieNotDefinedLabel?: string | null;
  cookieAcceptedLabel?: string | null;
  cookieDeclinedLabel?: string | null;
  cookieCustomLabel?: string | null;
  cookieSettingsButtonLabel?: string | null;
  cookieMetaTitle: string;
  cookieMetaDescription: string;
  cookieMetaImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  favicon?: T;
  websiteJsonLd?:
    | T
    | {
        name?: T;
        description?: T;
        alternateNames?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  organizationJsonLd?:
    | T
    | {
        name?: T;
        legalName?: T;
        description?: T;
        email?: T;
        telephone?: T;
        streetAddress?: T;
        addressLocality?: T;
        addressCountry?: T;
        socialProfiles?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  additionalJsonLd?:
    | T
    | {
        entries?:
          | T
          | {
              name?: T;
              enabled?: T;
              data?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  servicesLabel?: T;
  informationLabel?: T;
  turkmenLanguageLabel?: T;
  englishLanguageLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  cookiePolicyLabel?: T;
  privacyPolicyLabel?: T;
  copyright?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  location?: T;
  headline?: T;
  supportingText?: T;
  email?: T;
  copySuccessLabel?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-production_select".
 */
export interface HomeProductionSelect<T extends boolean = true> {
  projects?:
    | T
    | {
        clientName?: T;
        projectName?: T;
        coverImage?: T;
        video?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-brand-statement_select".
 */
export interface HomeBrandStatementSelect<T extends boolean = true> {
  statement?: T;
  marqueeText?: T;
  desktopCoverImage?: T;
  desktopVideo?: T;
  mobileCoverImage?: T;
  mobileVideo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-services_select".
 */
export interface HomeServicesSelect<T extends boolean = true> {
  eyebrow?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-process_select".
 */
export interface HomeProcessSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-header_select".
 */
export interface ServicesHeaderSelect<T extends boolean = true> {
  title?: T;
  introduction?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-intro_select".
 */
export interface AboutIntroSelect<T extends boolean = true> {
  statement?: T;
  image?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-capabilities_select".
 */
export interface AboutCapabilitiesSelect<T extends boolean = true> {
  capabilitiesHeading?: T;
  capabilitiesText?: T;
  clientsHeading?: T;
  clients?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-contact_select".
 */
export interface AboutContactSelect<T extends boolean = true> {
  contactHeading?: T;
  contactLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  officeHeading?: T;
  address?: T;
  hoursHeading?: T;
  workingDays?: T;
  workingHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  privacyTitle?: T;
  privacyLastUpdatedLabel?: T;
  privacyLastUpdated?: T;
  privacySections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  privacyMetaTitle?: T;
  privacyMetaDescription?: T;
  privacyMetaImage?: T;
  cookieTitle?: T;
  cookieOverviewLabel?: T;
  cookieOverviewContent?: T;
  cookieDomainLabel?: T;
  cookieDomain?: T;
  cookieConsentSectionLabel?: T;
  cookieCurrentStateLabel?: T;
  cookieConsentIdLabel?: T;
  cookieConsentDateLabel?: T;
  cookieNotDefinedLabel?: T;
  cookieAcceptedLabel?: T;
  cookieDeclinedLabel?: T;
  cookieCustomLabel?: T;
  cookieSettingsButtonLabel?: T;
  cookieMetaTitle?: T;
  cookieMetaDescription?: T;
  cookieMetaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug: 'users' | 'media' | 'services' | 'exports' | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}